#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;
#if defined(__cplusplus)
extern "C" {
#endif

extern void _AXNODE_myel_reg(void);
extern void _AXNODE_unmyel_reg(void);
extern void _CaPump_reg(void);
extern void _DNav18_reg(void);
extern void _KA14_reg(void);
extern void _KA34_reg(void);
extern void _NaCaPump_reg(void);
extern void _NaV7_reg(void);
extern void _NaV9_reg(void);
extern void _Nakpump_reg(void);
extern void _NakpumpSchild_reg(void);
extern void _RattayAberham_reg(void);
extern void _SK_reg(void);
extern void _caext_reg(void);
extern void _caextscale_reg(void);
extern void _caextscale_node_reg(void);
extern void _caextscale_nonnode_reg(void);
extern void _caexttest_reg(void);
extern void _caint_reg(void);
extern void _caintscale_reg(void);
extern void _cainttest_reg(void);
extern void _cal_reg(void);
extern void _can_reg(void);
extern void _cat_reg(void);
extern void _extrapump_reg(void);
extern void _fpump_reg(void);
extern void _gaines_internode_FLUTSTIN_reg(void);
extern void _gaines_internode_MYSA_reg(void);
extern void _gaines_node_reg(void);
extern void _h_reg(void);
extern void _im_reg(void);
extern void _k_ion_dynamics_reg(void);
extern void _k_ion_dynamics_tigerholm_reg(void);
extern void _ka_reg(void);
extern void _kca_reg(void);
extern void _kd_reg(void);
extern void _kdr_reg(void);
extern void _kdrTiger_reg(void);
extern void _kds_reg(void);
extern void _kext_reg(void);
extern void _kexternal_reg(void);
extern void _kf_reg(void);
extern void _kld_node_reg(void);
extern void _kld_nonnode_reg(void);
extern void _kna_reg(void);
extern void _ks_reg(void);
extern void _leak_reg(void);
extern void _leakSchild_reg(void);
extern void _na_ion_dynamics_reg(void);
extern void _na_ion_dynamics_tigerholm_reg(void);
extern void _nadifl_reg(void);
extern void _naext_reg(void);
extern void _naf_reg(void);
extern void _naf97_reg(void);
extern void _naf97mean_reg(void);
extern void _nahh_reg(void);
extern void _nald_node_reg(void);
extern void _nald_nonnode_reg(void);
extern void _nas_reg(void);
extern void _nas97_reg(void);
extern void _nas97mean_reg(void);
extern void _nattxs_reg(void);
extern void _nav1p9_reg(void);
extern void _train_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," \"AXNODE_myel.mod\"");
    fprintf(stderr," \"AXNODE_unmyel.mod\"");
    fprintf(stderr," \"CaPump.mod\"");
    fprintf(stderr," \"DNav18.mod\"");
    fprintf(stderr," \"KA14.mod\"");
    fprintf(stderr," \"KA34.mod\"");
    fprintf(stderr," \"NaCaPump.mod\"");
    fprintf(stderr," \"NaV7.mod\"");
    fprintf(stderr," \"NaV9.mod\"");
    fprintf(stderr," \"Nakpump.mod\"");
    fprintf(stderr," \"NakpumpSchild.mod\"");
    fprintf(stderr," \"RattayAberham.mod\"");
    fprintf(stderr," \"SK.mod\"");
    fprintf(stderr," \"caext.mod\"");
    fprintf(stderr," \"caextscale.mod\"");
    fprintf(stderr," \"caextscale_node.mod\"");
    fprintf(stderr," \"caextscale_nonnode.mod\"");
    fprintf(stderr," \"caexttest.mod\"");
    fprintf(stderr," \"caint.mod\"");
    fprintf(stderr," \"caintscale.mod\"");
    fprintf(stderr," \"cainttest.mod\"");
    fprintf(stderr," \"cal.mod\"");
    fprintf(stderr," \"can.mod\"");
    fprintf(stderr," \"cat.mod\"");
    fprintf(stderr," \"extrapump.mod\"");
    fprintf(stderr," \"fpump.mod\"");
    fprintf(stderr," \"gaines_internode_FLUTSTIN.mod\"");
    fprintf(stderr," \"gaines_internode_MYSA.mod\"");
    fprintf(stderr," \"gaines_node.mod\"");
    fprintf(stderr," \"h.mod\"");
    fprintf(stderr," \"im.mod\"");
    fprintf(stderr," \"k_ion_dynamics.mod\"");
    fprintf(stderr," \"k_ion_dynamics_tigerholm.mod\"");
    fprintf(stderr," \"ka.mod\"");
    fprintf(stderr," \"kca.mod\"");
    fprintf(stderr," \"kd.mod\"");
    fprintf(stderr," \"kdr.mod\"");
    fprintf(stderr," \"kdrTiger.mod\"");
    fprintf(stderr," \"kds.mod\"");
    fprintf(stderr," \"kext.mod\"");
    fprintf(stderr," \"kexternal.mod\"");
    fprintf(stderr," \"kf.mod\"");
    fprintf(stderr," \"kld_node.mod\"");
    fprintf(stderr," \"kld_nonnode.mod\"");
    fprintf(stderr," \"kna.mod\"");
    fprintf(stderr," \"ks.mod\"");
    fprintf(stderr," \"leak.mod\"");
    fprintf(stderr," \"leakSchild.mod\"");
    fprintf(stderr," \"na_ion_dynamics.mod\"");
    fprintf(stderr," \"na_ion_dynamics_tigerholm.mod\"");
    fprintf(stderr," \"nadifl.mod\"");
    fprintf(stderr," \"naext.mod\"");
    fprintf(stderr," \"naf.mod\"");
    fprintf(stderr," \"naf97.mod\"");
    fprintf(stderr," \"naf97mean.mod\"");
    fprintf(stderr," \"nahh.mod\"");
    fprintf(stderr," \"nald_node.mod\"");
    fprintf(stderr," \"nald_nonnode.mod\"");
    fprintf(stderr," \"nas.mod\"");
    fprintf(stderr," \"nas97.mod\"");
    fprintf(stderr," \"nas97mean.mod\"");
    fprintf(stderr," \"nattxs.mod\"");
    fprintf(stderr," \"nav1p9.mod\"");
    fprintf(stderr," \"train.mod\"");
    fprintf(stderr, "\n");
  }
  _AXNODE_myel_reg();
  _AXNODE_unmyel_reg();
  _CaPump_reg();
  _DNav18_reg();
  _KA14_reg();
  _KA34_reg();
  _NaCaPump_reg();
  _NaV7_reg();
  _NaV9_reg();
  _Nakpump_reg();
  _NakpumpSchild_reg();
  _RattayAberham_reg();
  _SK_reg();
  _caext_reg();
  _caextscale_reg();
  _caextscale_node_reg();
  _caextscale_nonnode_reg();
  _caexttest_reg();
  _caint_reg();
  _caintscale_reg();
  _cainttest_reg();
  _cal_reg();
  _can_reg();
  _cat_reg();
  _extrapump_reg();
  _fpump_reg();
  _gaines_internode_FLUTSTIN_reg();
  _gaines_internode_MYSA_reg();
  _gaines_node_reg();
  _h_reg();
  _im_reg();
  _k_ion_dynamics_reg();
  _k_ion_dynamics_tigerholm_reg();
  _ka_reg();
  _kca_reg();
  _kd_reg();
  _kdr_reg();
  _kdrTiger_reg();
  _kds_reg();
  _kext_reg();
  _kexternal_reg();
  _kf_reg();
  _kld_node_reg();
  _kld_nonnode_reg();
  _kna_reg();
  _ks_reg();
  _leak_reg();
  _leakSchild_reg();
  _na_ion_dynamics_reg();
  _na_ion_dynamics_tigerholm_reg();
  _nadifl_reg();
  _naext_reg();
  _naf_reg();
  _naf97_reg();
  _naf97mean_reg();
  _nahh_reg();
  _nald_node_reg();
  _nald_nonnode_reg();
  _nas_reg();
  _nas97_reg();
  _nas97mean_reg();
  _nattxs_reg();
  _nav1p9_reg();
  _train_reg();
}

#if defined(__cplusplus)
}
#endif
